<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('m_news')->insert([
            ['layout_id' => 1, 'status' => 1],
            ['layout_id' => 2, 'status' => 1],
            ['layout_id' => 5, 'status' => 1],
        ]);

        DB::table('m_news_translation')->insert([
            ['slug' => 'press/ve-chung-toi', 'title' => 'Về chúng tôi', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => 'Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản. Đoạn văn bản này không những đã tồn tại năm thế kỉ, mà khi được áp dụng vào tin học văn phòng, nội dung của nó vẫn không hề bị thay đổi. Nó đã được phổ biến trong những năm 1960 nhờ việc bán những bản giấy Letraset in những đoạn Lorem Ipsum, và gần đây hơn, được sử dụng trong các ứng dụng dàn trang, như Aldus PageMaker. Trái với quan điểm chung của số đông, Lorem Ipsum không phải chỉ là một đoạn văn bản ngẫu nhiên. Người ta tìm thấy nguồn gốc của nó từ những tác phẩm văn học la-tinh cổ điển xuất hiện từ năm 45 trước Công Nguyên, nghĩa là nó đã có khoảng hơn 2000 tuổi. Một giáo sư của trường Hampden-Sydney College (bang Virginia - Mỹ) quan tâm tới một trong những từ la-tinh khó hiểu nhất, "consectetur", trích từ một đoạn của Lorem Ipsum, và đã nghiên cứu tất cả các ứng dụng của từ này trong văn học cổ điển, để từ đó tìm ra nguồn gốc không thể chối cãi của Lorem Ipsum. Thật ra, nó được tìm thấy trong các đoạn 1.10.32 và 1.10.33 của "De Finibus Bonorum et Malorum" (Đỉnh tối thượng của Cái Tốt và Cái Xấu) viết bởi Cicero vào năm 45 trước Công Nguyên. Cuốn sách này là một luận thuyết đạo lí rất phổ biến trong thời kì Phục Hưng. Dòng đầu tiên của Lorem Ipsum, "Lorem ipsum dolor sit amet..." được trích từ một câu trong đoạn thứ 1.10.32.', 'language_id' => 1, 'translation_id' => 1],
            ['slug' => 'press/about-us', 'title' => 'About Us', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => 'Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản. Đoạn văn bản này không những đã tồn tại năm thế kỉ, mà khi được áp dụng vào tin học văn phòng, nội dung của nó vẫn không hề bị thay đổi. Nó đã được phổ biến trong những năm 1960 nhờ việc bán những bản giấy Letraset in những đoạn Lorem Ipsum, và gần đây hơn, được sử dụng trong các ứng dụng dàn trang, như Aldus PageMaker. Trái với quan điểm chung của số đông, Lorem Ipsum không phải chỉ là một đoạn văn bản ngẫu nhiên. Người ta tìm thấy nguồn gốc của nó từ những tác phẩm văn học la-tinh cổ điển xuất hiện từ năm 45 trước Công Nguyên, nghĩa là nó đã có khoảng hơn 2000 tuổi. Một giáo sư của trường Hampden-Sydney College (bang Virginia - Mỹ) quan tâm tới một trong những từ la-tinh khó hiểu nhất, "consectetur", trích từ một đoạn của Lorem Ipsum, và đã nghiên cứu tất cả các ứng dụng của từ này trong văn học cổ điển, để từ đó tìm ra nguồn gốc không thể chối cãi của Lorem Ipsum. Thật ra, nó được tìm thấy trong các đoạn 1.10.32 và 1.10.33 của "De Finibus Bonorum et Malorum" (Đỉnh tối thượng của Cái Tốt và Cái Xấu) viết bởi Cicero vào năm 45 trước Công Nguyên. Cuốn sách này là một luận thuyết đạo lí rất phổ biến trong thời kì Phục Hưng. Dòng đầu tiên của Lorem Ipsum, "Lorem ipsum dolor sit amet..." được trích từ một câu trong đoạn thứ 1.10.32.', 'language_id' => 2, 'translation_id' => 1],

            ['slug' => 'press/lien-he', 'title' => 'Liên hệ', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtVN </div></div>', 'language_id' => 1, 'translation_id' => 2],
            ['slug' => 'press/contact', 'title' => 'Contact', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtEN </div></div>', 'language_id' => 2, 'translation_id' => 2],

            ['slug' => 'press/tin-tuc1', 'title' => 'Tin Tức', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtVN </div></div>', 'language_id' => 1, 'translation_id' => 3],
            ['slug' => 'press/news1', 'title' => 'News', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtEN </div></div>', 'language_id' => 2, 'translation_id' => 3],
            ['slug' => 'press/tin-tuc2', 'title' => 'Tin Tức', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtVN </div></div>', 'language_id' => 1, 'translation_id' => 3],
            ['slug' => 'press/news2', 'title' => 'News', 'meta_title' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_keyword' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'meta_description' => 'lorem, ipsum, lorem ipsum, ipsum lorem', 'content' => '<div class="accordion"> <div id="headingOne"> <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> This is top question, the users always ask? </a> </div><div id="collapseOne" class="collapse show" aria-labelledby="headingOne" > abc </div></div><div class="accordion" > <div id="headingTwo"> <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"> Can i pay money for VIP member? </a> </div><div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" > def </div></div><div class="accordion"> <div id="headingThree"> <a href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree"> Change my children name? </a> </div><div id="collapseThree" class="collapse" aria-labelledby="headingThree" > ghtEN </div></div>', 'language_id' => 2, 'translation_id' => 3]
        ]);

        DB::table('m_menu')->insert([
            ['news_id' => 1, 'sort' => 1, 'position' => '1','layout_id' => null],
            ['news_id' => 2, 'sort' => 2, 'position' => '1','layout_id' => null],
            ['news_id' => 1, 'sort' => 1, 'position' => '2','layout_id' => null],
            ['news_id' => 2, 'sort' => 2, 'position' => '2','layout_id' => null],
            ['news_id' => 1, 'sort' => 1, 'position' => '3','layout_id' => null],
            ['news_id' => 2, 'sort' => 2, 'position' => '3','layout_id' => null],
            ['news_id' => 1, 'sort' => 2, 'position' => '4','layout_id' => null],
            ['news_id' => 2, 'sort' => 2, 'position' => '4','layout_id' => null],
        ]);

        DB::table('m_menu_translation')->insert([
            ['slug' => 'press/ve-chung-toi', 'name' => 'Về chúng tôi', 'language_id' => 1, 'translation_id' => 1],
            ['slug' => 'press/aboutus', 'name' => 'About Us', 'language_id' => 2, 'translation_id' => 1],
            ['slug' => 'press/lien-he', 'name' => 'Liên hệ', 'language_id' => 1, 'translation_id' => 2],
            ['slug' => 'press/contact', 'name' => 'Contact', 'language_id' => 2, 'translation_id' => 2],
            ['slug' => 'press/ve-chung-toi', 'name' => 'Về chúng tôi', 'language_id' => 1, 'translation_id' => 3],
            ['slug' => 'press/aboutus', 'name' => 'About Us', 'language_id' => 2, 'translation_id' => 3],
            ['slug' => 'press/contact', 'name' => 'Liên hệ', 'language_id' => 1, 'translation_id' => 4],
            ['slug' => 'press/lien-he', 'name' => 'Contact', 'language_id' => 2, 'translation_id' => 4],
            ['slug' => 'press/ve-chung-toi', 'name' => 'Về chúng tôi', 'language_id' => 1, 'translation_id' => 5],
            ['slug' => 'press/aboutus', 'name' => 'About Us', 'language_id' => 2, 'translation_id' => 5],
            ['slug' => 'i/lien-he', 'name' => 'Liên hệ', 'language_id' => 1, 'translation_id' => 6],
            ['slug' => 'i/contact', 'name' => 'Contact', 'language_id' => 2, 'translation_id' => 6],
            ['slug' => 'i/lien-he', 'name' => 'Liên hệ', 'language_id' => 1, 'translation_id' => 7],
            ['slug' => 'i/contact', 'name' => 'Contact', 'language_id' => 2, 'translation_id' => 7],
            ['slug' => 'i/lien-he', 'name' => 'Liên hệ', 'language_id' => 1, 'translation_id' => 8],
            ['slug' => 'i/contact', 'name' => 'Contact', 'language_id' => 2, 'translation_id' => 8]
        ]);

    }
}
